### ISSUE TITLE
errors in resulting path on linux

### ISSUE THREAD

**Issue by stockleyy** [jslay88/qbt_migrate#1]
I'm replacing "Drive:" on Windows to "/mnt/Drive" on Linux. This is the resulting path:

/mnt/Drive\directory\subdirectory\/

-there are still backward slashes in the full path
-trailing slashes

**Comment by jslay88** [comment]
I see where the issue is. I'll get it updated shortly.

**Comment by jslay88** [comment]
If the trailing slashes are an issue, let me know. It shouldn't be an issue though, as we are just setting a directory location, and both *nix and Windows should handle trailing slashes appropriately.

**Comment by jslay88** [comment]
I see another issue when going from linxu to windows. Working on another fix.
