### ISSUE TITLE
Work even when fastresume doesn't have all the contents you expect

### ISSUE THREAD

**Issue by wambiditu** [jslay88/qbt_migrate#12]
Some of my fastresume files are missing at least one path.  I think the best action is to change what I know to change, if it exists, and leave everything else alone.  This works OK if both paths are present, or both are missing.  But in the case where only one is present, currently the other one isn't getting corrected.

I think I fixed this on my copy by commenting out the if and raise at lines 109-110 of classes.py
```
        #if 'save_path' not in self._data or 'qBt-savePath' not in self._data:
        #    raise ValueError('Missing required keys for a qBittorrent .fastresume file')
```
and by adding an if statement at line 139:
```
        if not path:
            return
```

**Comment by jslay88** [comment]
Please fork and open a PR. Thanks.

**Comment by jslay88** [comment]
#18 resolves
