### ISSUE TITLE
win -> Linux requires going 1 directory away from the Drive letter

### ISSUE THREAD

**Issue by Reverse256** [jslay88/qbt_migrate#14]
Hello,

This tool looks very useful.

One issue I ran into.

'-e X:\\' fails

user@computer:/dev/shm$ qbt_migrate -e X:\ -n /mnt/z -t Linux
usage: qbt_migrate [-h] [-e EXISTING_PATH] [-n NEW_PATH] [-t {Windows,Linux,Mac}] [-b BT_BACKUP_PATH] [-s] [-l {DEBUG,INFO}]
qbt_migrate: error: unrecognized arguments: /mnt/z

'-e X:\a' works

user@computer:/dev/shm$ qbt_migrate -e X:\a -n /mnt/z -t Linux
BT_Backup Path (/home/user/.local/share/data/qBittorrent/BT_backup):

Thank you for this tool

**Comment by Reverse256** [comment]
Submitted PR to update documentation for the repo in its current condition


Double backslash works: (also I needed trailing '/' after 'z')

qbt_migrate -e X:\\ -n /mnt/z/ -t Linux

**Comment by jslay88** [comment]
#18 resolves
