### ISSUE TITLE
[Feature Request] Make it possible to change only part of the path.

### ISSUE THREAD

**Issue by varoOP** [jslay88/qbt_migrate#23]
For example, if I am migrating my qBitorrent session but destination Linux install has different username, then the entire path remains the same but only the username changes.

Since I have a lot of sub-directories, changing the full path would not be ideal.

A regex option to only replace certain pattern matching string with another string would be amazing. This way I coud cutomize it to replace username in my case and I am sure other people coud find other uses for the same.

**Comment by jslay88** [comment]
See if this suits your needs. #29
