### ISSUE TITLE
KeyError at self._data[key] (classes.py@154)

### ISSUE THREAD

**Issue by ivanlewin** [jslay88/qbt_migrate#32]
Running the script I found the following error: `qBt-savePath` was not a key of `self._data` and it resulted in a KeyError.
To avoid it, I commented line 154 of [classes.py](https://github.com/jslay88/qbt_migrate/blob/master/qbt_migrate/classes.py):
`self.logger.debug(f"Setting {key}... Old: {self._data[key]}, New: {path}, Target OS: {target_os}")`

Btw, I can't thank you enough for your work! I have more than 100 torrents that I was moving from Windows to Linux and this tool was extremely useful

**Comment by jslay88** [comment]
You can install this version ahead of a release with the following
```
pip install git+https://github.com/jslay88/qbt_migrate.git@master
```
