### ISSUE TITLE
Hi I need some help

### ISSUE THREAD

**Issue by AlexanderHel** [jslay88/qbt_migrate#43]
I already followed the wiki but for some reason it didn't work for me, hope I'm not a bother

My previous folder path is J:\Anime\ I want to change to G:\Anime\

I followed the guide but got this error, also when I reopen qbit nothing changed

![image](https://user-images.githubusercontent.com/99399435/163664896-6096148d-ae85-4e0e-9e16-0821b79fa218.png)

**Comment by jslay88** [comment]
Try it with this branch and report back.

```
pip install git+https://github.com/jslay88/qbt_migrate.git@fix-more-missing-qbt-save-path
```

**Comment by AlexanderHel** [comment]
Still the same

![image](https://user-images.githubusercontent.com/99399435/163673046-944dba4f-8547-45f9-adf5-68ac59a4c384.png)

**Comment by jslay88** [comment]
Hmmm. Strangely enough, it looks like it's still running old code from what the screenshot is showing. The line it's erroring out on, has been updated, and it's not showing the update. 

Let's try removing it first and then reinstalling. 

```
pip uninstall qbt_migrate

pip install --no-cache-dir -U git+https://github.com/jslay88/qbt_migrate.git@fix-more-missing-qbt-save-path

```

**Comment by AlexanderHel** [comment]
The error still there, wonder if it's my pc problems lol

![image](https://user-images.githubusercontent.com/99399435/163683781-9f8b3498-c995-4e00-a1d0-d9ef935780dc.png)

**Comment by jslay88** [comment]
Well, it looks like it got the correct code this time at least. Only thing I can think of, is you have a fastresume that doesnt have a `savePath` key, which is not a valid fastresume file. 

Can you share one of the backup archives it creates with me so that I can further troubleshoot your issue?

**Comment by AlexanderHel** [comment]
Sure, here is it

https://drive.google.com/file/d/1n5QnJrywzYvQR5LvqEKS52sI-9vDnzru/view?usp=sharing

**Comment by jslay88** [comment]
OK, the the uninstall and reinstall again and give it a shot.

**Comment by AlexanderHel** [comment]
It's working now thank you very much ^^
