### ISSUE TITLE
Type error when specifing bt backup folder on command line

### ISSUE THREAD

**Issue by wambiditu** [jslay88/qbt_migrate#57]
When supplying a backup path on the command line, I get a type error crash on the line `if not self.bt_backup_path.is_dir():` because the type is string, but it's expecting a Path.  I addressed this on my local copy by putting `self.bt_backup_path = Path(self.bt_backup_path)` on the line immediately above it, but maybe this wouldn't work in cases where the path is determined other ways.

(qbt_migrate 2.3.0, python 3.10.4)

**Comment by jslay88** [comment]
I've fixed the interfacing side of it from the CLI with #60 , while I think about how I want to refactor `QBTBatchMove.bt_backup_path` as a whole.
