### ISSUE TITLE
Can you change the download path too?

### ISSUE THREAD

**Issue by wambiditu** [jslay88/qbt_migrate#58]
After moving my qBittorrent files to a computer with a newer version of qBittorrent (4.4.1) and then launching qBittorrent, I noticed my Downloads (and thus home) was getting rapidly filled with intermediate torrented files.

On investigation, I noticed several of the fastresume files had been modified by qBittorrent, and a new key added to them: `qBt-downloadPath`, with the value being a temp folder in my Downloads folder.  Yuck.  (I think this is due to a recent bug in qBittorrent, where it writes the config file with `Downloads\TempPathEnabled=true`, but with no `Downloads\TempPath` line at all)

Now I have all these fastresume files with bad download paths.  Can qbt_migrate be modified to fix them?

Edit: In the short term, I'm considering soft-linking the ~/Downloads/temp folder to where the temporary downloads were supposed to be, on another drive.

**Comment by jslay88** [comment]
If you know a little python, you can adapt it simple enough. The `FastResume` class can be used to modify any key and value of a `fastresume` file. 

It will be a bit before I could probably get around to understanding the issue with this particular key, unless its just a "set same-as" with the others being handled by qbt_migrate.

**Comment by jslay88** [comment]
Looks like it has to do with auto managed torrents, but can also just be set blindly along with `save_path` and `qBt-savePath`. Will add some changes to accommodate this.

**Comment by jslay88** [comment]
Please give this a try and report back your results.

```Bash
pip uninstall -y qbt_migrate
pip install -U --no-cache-dir git+https://github.com/jslay88/qbt_migrate.git@qbt-downloadPath
```
