### ISSUE TITLE
DOES NOT WORK

### ISSUE THREAD

**Issue by stderr-to-devnull** [jslay88/qbt_migrate#61]
Executed it to change drive letter with appropriate arguments as given in the examples. It informs me that it found the current drive letter in x fastresume files. Then I start qbt and I see hundreds of my torrents "moving" and they are being moved to the OLD drive letter (the one I just tried to change / update with this tool). Sure enough, I see my directories re-appear on the old drive.

**Comment by stderr-to-devnull** [comment]
Upon further analysis, it looks like it doesn't work for any torrents that are still in `uploading` state, possibly this extends to any other torrent that is not in `finished` state. Unfortunately, the documentation does not mention any of this. So now I am manually checking and moving from qbt interface hundreds of torrents, one by one.

**Comment by stderr-to-devnull** [comment]
- I made sure qbt was closed
- I made sure all the data was in the new drive (checked myself)

As I mentioned in my 2nd comment, the script does not take into account any torrent that was still in `seeding` state. Maybe the fastresume files are different for them, no idea. But this is not explained.

What qbt was doing after opening was actively _moving_ the content of the torrents from the _new_ location (where I copied them) to the _old_ location. I have no idea how or why it was doing that but basically hundreds of  torrents were in the `moving` status. Again, they were being moved from the `new` drive back to the `old` drive.

So whatever this script is designed to do is not working properly or does not cover the torrents in the `seeding` state.

Before arbitrarily _assuming_ that I did something wrong you could have easily tested this behavior which I explained in detail.

**Comment by jslay88** [comment]
We don’t detect anything different between seeding or not (see demo gif).

qbt also does not actively move content like that on start. If anything,
the files are missing, and it tries to start downloading them again.

The behaviors you describe do not match the tool or qbt.

Regardless, post a fastresume file from the initial backup zip, along with
its modified one, for me to take a look at.

**Comment by nokicheru** [comment]
I also have the same issue as OP. I use the script, move my files to their new destination and they get moved back to the starting path by qbittorrent when opening it.
I also made sure that qbittorrent and its' process were closed before starting the script.
Interestingly the fastresume file, that was changed by the script, gets modified again when opening qbittorrent.

I'll attach the fastresume file that was backed up by the script, the file after it was changed by the script and the same file after I opened qbittorrent again and it was changed by that again and the downloaded files were moved back to the original path.
[fastresumefiles.zip](https://github.com/jslay88/qbt_migrate/files/10310662/fastresumefiles.zip)

**Comment by jslay88** [comment]
Sweet, thanks for the files, will take a look when I get a chance.

What version of qbt are you using?

**Comment by jslay88** [comment]
Give this a shot and let me know

```
pip uninstall -y qbt_migrate
pip install -U --no-cache-dir git+https://github.com/jslay88/qbt_migrate.git@qbt_save_path_fix
```

**Comment by nokicheru** [comment]
It seems to work now, I'm on version 4.5.0 of qbittorrent.

Thanks for the quick fix!

**Comment by jslay88** [comment]
Files make a world of difference. :)
