### ISSUE TITLE
Feature Request - Update Announce URL

### ISSUE THREAD

**Issue by jonboy345** [jslay88/qbt_migrate#7]
So, I started down the path of working on doing this myself but realized I don't have the skills to accomplish this...

So there's a popular tracker that is moving domains and as such the announce URL will need to be updated to the new URL.

Would it be possible to adapt this script to allow the mass update of Announce URLs in the same manner as the save path?

Glad to help test as well.

Huge thanks on all of the work on this thus far, huge time saver for me and others I'm sure.

**Comment by jslay88** [comment]
But you do!

Fork the repo, and start putting print/logging statements in place and play with the files. 

https://github.com/jslay88/qbt_migrate/blob/7340dd8900816d72b0a38538740ad9985a361593/qbt_migrate/classes.py#L98

Print/log out the dictionary `self._data` here and find the key you need. Then, add a new method for changing your Announce URLs similar to the set_save_path method.

Then you can just import FastResume into your own script and load up your specific files.

**Comment by jonboy345** [comment]
Okay, well... I guess the real answer is I don't have the time.

Luckily after more digging, I found this tool that will change tracker URLs in bulk: https://github.com/rumanzo/qbtchangetracker

Thanks again.
