### ISSUE TITLE
Please help me run this script

### ISSUE THREAD

**Issue by vangeliis** [jslay88/qbt_migrate#8]
Hi,

Thank you for creating this nifty tool. I want to change the path from Win to MacOS.

Please can you help me? I run the classes.py but get the following error:

from .methods import discover_bt_backup_path, convert_slashes
ModuleNotFoundError: No module named '__main__.methods'; '__main__' is not a package

I would really appreciate some simple and clear instructions.

Thank you ever so much,
vangeliis

**Comment by jslay88** [comment]
Follow the README

**Comment by vangeliis** [comment]
Hi,

I have very little knowledge of python so more detailed instructions would be greatly appreciated. 

"Run the script and follow prompts or use CLI arguments with command qbt_migrate"

What script am I supposed to run? the setup.py ? and where do I change the default path for the BT_backup folder?

Many thanks,
vangeliis

**Comment by jslay88** [comment]
qbt_migrate as described and shown in the README. Not sure how else to
describe running it.  It clearly shows how to call it by name if installed
by pip.

**Comment by jslay88** [comment]
README shows arguments for changing default path as well. Please read the
README before asking anymore questions already covered there.
